[build]
  command = "cd frontend && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
